build the car:
  script:
      - mkdir build
      - cd build
      - touch car.txt
      - echo "chassis" > car.txt
      - echo "engine" > car.txt
      - echo "wheels" > car.txt

test the car:
  script:
    - test -f build/car.txt
    - cd build
    - grep "chassis" car.txt
    - grep "engine" car.txt
    - grep "wheels" car.txt
    
