stages:
  - prep
  - build
  - test
  
prepare the car:
  stage: prep
  script:
    - mkdir build
    - cd build
    - touch car.txt
  artifacts:
    paths:
      - build/car.txt

spackulous:
  stage: build
  script:
    - mkdir meta
    - cd meta
    - echo $sai saketh >spackulous.txt
  artifacts:
    paths:
      - meta/spackulous.txt
    
build the car:
  stage: build  
  script:
    - cd build
    - echo "chassis" >> car.txt
    - echo "engine" >> car.txt
    - echo "wheels" >> car.txt
  artifacts:
    paths:
      - build/car.txt
  

test the car:
  stage: test
  script:
    - test -f build/car.txt
    - cd build
    - grep "chassis" car.txt
    - grep "engine" car.txt
    - grep "wheels" car.txt
    
